### ISSUE TITLE
[Feature] A `PackageReference` with `ReferenceOutputAssembly=false` should not be a dep

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#132]
**Is your feature request related to a problem? Please describe.**
A `ProjectReference` with `ReferenceOutputAssembly` set to `false` should not be captured as a dependency.

From the [docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#projectreference)

| ReferenceOutputAssembly | Optional boolean. If set to false, does not include the output of the referenced project as a Reference of this project, but still ensures that the other project builds before this one. Defaults to true. |
| :-- | :-- |

**Comment by AgentEnder** [comment]
What would the use case for this be? For the purpose of target dependencies and such it sounds like the current behavior may still be desired

**Comment by pemsbr** [comment]
I would like to ensure that a project builds before another one

**Comment by AgentEnder** [comment]
Is the reasoning behind wanting the build ordering due to an artifact being created or similar?

**Comment by pemsbr** [comment]
Yep! Here's the scenario:
- Project A (classlib) has an msbuild target that runs (`dotnet run --no-build`) Project B (console) to generate some source files.
- Project A needs Project B (console) to be built beforehand.
- Project A cannot (should not) reference Project B because of how we defined our tags

**Comment by AgentEnder** [comment]
@pemsbr Sorry for just getting back to this. Would I be correct in saying that the issue here is not that Nx is labeling the dep, but rather the enforce-module-boundaries logic is complaining about the dependency? 

For runtime purposes since Project A requires Project B be built, it would be closer to an implicit dependency as we do w/ cypress / e2e projects in the main Nx repo. Given this, would it be a good solution in your mind if `nx-dotnet` labelled references of these types as implicit in the dep-graph, and didn't check them in the enforce-module-boundaries logic?

**Comment by AgentEnder** [comment]
This was released in v1.5!
