### ISSUE TITLE
[Feature] Add support for .NET solution files when generating new projects

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#241]
**Is your feature request related to a problem? Please describe.**
Visual Studio and Visual Studio Code both handle .NET workspaces better when a solution file (.sln) is present. While they recognize all projects that exist in the workspace, neither IDE provides a full experience for project dependencies, installed NuGet packages, or proper IntelliSense unless the IDE has been opened with a solution file.

**Describe the solution you'd like**
The first dotnet project in a workspace should optionally add a solution file to the root of the workspace. This solution file can be created and later managed through the `dotnet sln` commands. The new project should be added to a solution folder mirroring the Nx folder layout or the root of the solution if the project is directly contained within apps/libs. Solution folder names should be normalized to PascalCase.

Later dotnet projects should optionally be added to the previously generated solution file (defaulting to inclusion if the solution file exists). These projects should also be added to a solution folder mirroring the Nx layout.

A new generator should be added that takes an existing .NET/Nx workspace and creates a solution file as described above, then adds all existing projects to the appropriate solution folders.

**Describe alternatives you've considered**
In my own workspace, I created a solution file named `workspace.sln` in the root folder of my Nx workspace. I've been manually keeping that solution file in-sync with the Nx workspace. This has worked for developer experience, but is rather tedious.

**Additional context**
I generally dislike the Nx distinction of apps and libs and how Nx keeps those two project types in separate directory trees. For my own solution file, I've mirrored the Nx filesystem except for the top level folders. This means that `apps/my-scope/A` and `libs/my-scope/A` live together in a solution folder named `MyScope`.

This feature works great for my predominantly .NET workspace. Visual Studio solutions have little-to-no support for non-dotnet projects, so any Node.js/Angular/etc. projects will be excluded, creating a fractured view of the workspace, especially as the number of non-dotnet projects grows. Still, the ease of use for developing .NET projects is greatly enhanced by solutions, and traditional Nx methods will continue to work for the remaining projects.

**Comment by AgentEnder** [comment]
Hey, this is a problem that I've thought about a bit... My fear w/ workspace root level solution files is how slow IDE's can get when they have many projects. Its possible that I'm just thinking prematurely, and it should just be added.

The alternatives that I had thought about are something more like 
```
> nx g @nx-dotnet/core:sln --project {p}

export default slnGenerator(tree, {project, outputPath}) {
    const csprojFiles = getConnectedNodesOnProjectGraph(project).map(x => findCsProjForNxProject(x));
    const absolutePath = path.resolve(project.root);
    execSync(`dotnet new sln`, {cwd: project.root});
	csprojFiles.forEach(file => {
        execSync(`dotnet sln add ${path.relative(absolutePath, file)}`)
    }
}
```

This could of course live alongside the workspace level solution 🤔

**Comment by bcallaghan-et** [comment]
Would that code identify isolated sub-graphs and create a solution file for each sub-graph? I'd considered doing something similarly myself, albeit manually. That's pretty similar to how we did it before introducing Nx to the mix. It won't be a long-term solution for us though, since we're planning on adding enough util/shared libs that it all becomes one massive graph again.

**Comment by AgentEnder** [comment]
Hey, I'm going to try to put together some thoughts here, but I'm aware that there are kind of a lot of them 🤷 

## Some form of project-graph based solution generator
Would look something like `nx g @nx-dotnet/core:sln --project {p}`, to function similar to `nx affected:sln`.

### Pros
- Users can generate a solution file to open in their IDEs that only contains relevant projects

### Cons
- "relevant" projects could easily grow to be **_most_** of the projects in a monorepo
- Much, much harder due to the things to think about.

### Additional Considerations

The below thoughts use this dep-graph as an example.
![image](https://user-images.githubusercontent.com/6933928/142515381-a968b5cf-dbb4-43fa-bd6f-f653147756cc.png)

So, `nx g @nx-dotnet/core:sln --project a` would generate a solution file with references to a, d, and f. The main problem with this, is changing D with the solution open could cause B to not build.

The user wouldn't see these in their IDE without B open, so we would need to have it in their solution.

One possible approach to this, would be to have an `--exclude` option to be able to manually exclude projects based on tags. This could theoretically be used like `nx g @nx-dotnet/core:sln --exclude scope:shared` to generate a .sln file without D, such that the user's changes would couldn't affect projects not loaded by the solution. This would of course, require that the user takes advantage of Nx's tagging mechanisms.

If that is the approach we take, maintaining the global sln file would still help in cases where "core" or shared libraries need to be modified. In a case like this, you may have a solution file generated for D that references projects A, B, & C as well as D. This solution file could leave out F, since it isn't impacted directly by edits to D, or A but that still feels sub-optimal since a developer would need to swap sln files to start work on a different area of the app.

## Maintaining a global, workspace level solution file

### Pros
- Dead simple to implement
- Users can open all projects in the monorepo in VS / Rider / etc really easily

### Cons
- Users can only easily open **_all_** projects, without maintaining a subset of solution files for themselves
- VS can really bog down w/ large solutions, not tried in other IDE's

**Comment by AgentEnder** [comment]
There is some additional commentary on solution files here (https://github.com/nx-dotnet/nx-dotnet/discussions/167), but I think that my statements above fall in line with that discussion too.

**Comment by bcallaghan-et** [comment]
I currently have a workspace-level solution file that contains 60 C# projects (my workspace also contains 2 Angular projects). Visual Studio is noticeably with this large solution than with a solution of 2-3 projects, but it still opens in ~12 seconds. VS Code didn't open any slower with the solution file than it did without the solution file.

Another feature worth considering if you want to do sub-graphs and smaller solution files is [solution filters](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2022). These files look and act like a solution file, but they are strictly a subset of the larger solution. "If new projects are added to the original solution after you create the solution filter file, they appear as unloaded projects in Solution Explorer." I don't know how useful it would be to automatically maintain solution filters; many teams may want to manage that themselves.

I already have a custom dotnet workspace-generator that I use to change some default build settings. If you decide this feature isn't worthwhile to the larger community, I can add my solution management ideas to that workspace-generator instead. It will certainly take less time for me to implement features that cover my exact use case than it would to implement more-generalized features for everyone.

**Comment by AgentEnder** [comment]
I think its worth checking if the workspace level solution file exists, and adding new projects to it at a minimum. We could write a guide or something for using solution filters, I hadn't considered them. Do you know how those impact performance?

**Comment by bcallaghan-et** [comment]
From the docs, solution filters claim to improve performance relative to a massive all-encompassing solution file. Filters only load the projects you select, rather than loading all projects.

**Comment by AgentEnder** [comment]
Interesting, I'll keep those in mind as a target for future dates. 

Do you want to take on the root level solution file? In my mind it would work like this:
Add a flag (--solution) to both project generators, optional. Takes either a string or boolean. 

If its a string, its a path to the solution file. This should be saved as a default parameter in nx.json (i.e. nx.json has a section like this after running generator with string flag)
```
{
    "generators": {
        "@nx-dotnet/core:app": {
            solution: "my-path/to-solution-file.sln"
        },
        "@nx-dotnet/core:lib": {
            solution: "my-path/to-solution-file.sln"
        }
    }
}
```

If its set to true: Check if solution file exists (perhaps default to something like `` `${npmScope}.workspace.sln` ``), if it does add to it, else create it.

If its set to false: Skip everything related to sln files

If its null (which is default): Check if solution file exists, add if present.

**Comment by bcallaghan-et** [comment]
I just pulled the latest version to try out the solution files. When generating an app with a test project, only the app project is added to the solution file. The test project should also be added.

**Comment by AgentEnder** [comment]
Good catch, should be patched up. Do you want to put in a PR for that?

**Comment by bcallaghan-et** [comment]
Yes, I can work on that today.

**Comment by t-ricci-delta** [comment]
Neither apps nor libs to me are added to the solution file, even if specified from command line:

`npx nx g @nx-dotnet/core:app my-api --template webapi --solutionfile MySolution.sln`

I tried with nx.json settings:

```

    "@nx-dotnet/core:app": {
      "solution": "my-path/to-solution-file.sln"
    },
    "@nx-dotnet/core:lib": {
      "solution": "my-path/to-solution-file.sln"
    }
```

and

```

    "@nx-dotnet/core:app": {
      "solutionFile": true
    },
    "@nx-dotnet/core:lib": {
      "solutionFile": true
    }
```


none worked and I still have a empty .sln file (I had to create it manually because it didn't create one automatically on init)

**Comment by AgentEnder** [comment]
@t-ricci-delta do you care to open an issue and provide the output of `nx-report` alongside this? That well help identify the cause. Thanks.

**Comment by t-ricci-delta** [comment]
> @t-ricci-delta do you care to open an issue and provide the output of `nx report` alongside this? That well help identify the cause. Thanks.

Here's the new issue: https://github.com/nx-dotnet/nx-dotnet/issues/280

thanks!
