### ISSUE TITLE
How to debug when running `nx serve` in vs-code?

### ISSUE THREAD

**Issue by senthanal** [nx-dotnet/nx-dotnet#396]
**Describe the bug**
While running the project with **npx nx serve myproject** in the vscode terminal, the debug is stopping at the breakpoints

**To Reproduce**

1. Setup a C# .NET webapi project template. The default project is WeatherForecast
2. Set a breakpoint at the GET method of WeatherForecastController
3. Run the project with **npx nx serve myproject**
4. Should open a browser with swagger api documentation
5. Try it our GET method.
6. No stopping at the breakpoint

**Expected behavior**
Should stop at the breakpoint

**Environment:**

- OS: Windows 11
- Browser: Chrome
- VS Code Version: 1.65.1
- NX version: 13.8.5
- @nx-dotnet/core: 1.9.5

**Comment by AgentEnder** [comment]
For debugging to work in vscode, you'd need to setup a launch profile to run the serve command and attach the debugger, or manually attach the debugger. By default, `nx-dotnet` is not responsible for debugging since its editor is independent. 

In general, the steps to debug the running process would be something along the lines of 
1. setup debug tool
2. launch dotnet program (via nx serve...)
3. attach debugger

This should help: https://stackoverflow.com/questions/60440765/how-can-i-attach-to-a-specific-process-in-visual-studio-code

**Comment by senthanal** [comment]
Hi, Thanks for pointing me in the right direction. I've updated my launch.json which helps to run the .NET application in Debug mode. Following is my launch.json
`
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": ".NET Core Launch (web)",
      "type": "coreclr",
      "request": "launch",
      "preLaunchTask": "build",
      "program": "${workspaceFolder}/dist/apps/api/<target framework>/<application>.dll",
      "args": [],
      "cwd": "${workspaceFolder}",
      "stopAtEntry": false,
      "serverReadyAction": {
        "action": "openExternally",
        "pattern": "\\bNow listening on:\\s+(https?://\\S+)"
      },
      "env": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "sourceFileMap": {
        "/Views": "${workspaceFolder}/Views"
      }
    }
  ]
}

`
