### ISSUE TITLE
[BUG] .NET directory and file naming conventions not followed

### ISSUE THREAD

**Issue by mgutz** [nx-dotnet/nx-dotnet#427]
**Describe the bug**

.NET naming conventions are not followed when creating app and library directories. This breaks C# snippets in my IDE which uses the directory as the namespace when adding classes, etc.

**To Reproduce**

1. Create an app using generator: `nx g @nx-dotnet/core:app ProductApi`

This creates `packages/product-api` package.  Note the project is named properly as `MyOrg.ProductApi.csproj`

**Expected behavior**

Folder name should be fully quallified and PascalCase like `MyOrg.ProductApi` to follow .NET naming conventions so VS Code extensions work properly.

**Comment by AgentEnder** [comment]
Hey @mgutz, sorry for just now getting back to you on this. This is an interesting case, I'd argue that the vs code extensions should make use of the .csproj files and such rather than relying so strictly on folder names 🤷. Given that they do though, we may be able to add a flag to generate the file path as requested.

This isn't really a bug on our end though, there was a deliberate decision that the plugin should follow Nx's standards for project placement. I'm going to change this over to an enhancement and leave some notes here. If you feel comfortable working on it, you are welcome to as it will be a little bit before I can.

- Add `pathScheme` flag to app, lib, and test generator schema.json files
	- Possible values: `nx`, `dotnet`
	- Default: `nx`
- Update schema.d.ts files for each generator with the new prop
- Update project generator and test-project-generator util files to take it into account when normalizing options.

**Comment by AgentEnder** [comment]
This is solved - See #464
