### ISSUE TITLE
[BUG] Output folder doubled

### ISSUE THREAD

**Issue by EelcoLos** [nx-dotnet/nx-dotnet#559]
**Describe the bug**
Running `npx nx run-many --target=build --parallel=true --projects=api,client --configuration=production` will result in a doubled output folder of nx-dotnet's api client versus angular clients output folder.
So now, i have a `/src/apps/api/dist/apps/api` folder. This is easily mitigated. However, it is different regarding other nx packages

**To Reproduce**

workspace/project.json:
```json
"api": {
			"$schema": "..\\..\\node_modules\\nx\\schemas\\project-schema.json",
			"root": "apps/api",
			"projectType": "application",
			"sourceRoot": "apps/api",
			"targets": {
				"build": {
					"executor": "@nx-dotnet/core:build",
					"outputs": ["{sourceRoot}/obj", "{options.output}"],
					"options": {
						"output": "dist/apps/api",
						"configuration": "Debug"
					},
					"configurations": {
						"production": {
							"configuration": "Release"
						}
					}
				},
}
```

1. have an nx-dotnet project building the api project
1. See 'error' / different output path

**Expected behavior**
I expected behavior to be similar to the angular option: 
```json
"client": {
			"$schema": "..\\..\\node_modules\\nx\\schemas\\project-schema.json",
			"projectType": "application",
			"root": "apps/client",
			"sourceRoot": "apps/client/src",
			"prefix": "",
			"targets": {
				"build": {
					"executor": "@angular-devkit/build-angular:browser",
					"outputs": ["{options.outputPath}"],
					"options": {
						"outputPath": "dist/apps/client",
//etc.
}
}
``` 
which outputs to `src/dist/apps/client`.

**Environment:**

- Version: 1.4/1.5
- Affected Packages: `@nx-dotnet/core` , `@angular-devkit/build-angular:browser`

**Additional context**
As I pointed out in the description, this is mitigable for the end-result, by updating all folders. I wonder if the separate behavior should stay though.

**Comment by AgentEnder** [comment]
We don't specify output in project.json or workspace.json by default due to some interesting quirks of dotnet cli. The recommendation on our side is that you configure output paths via the .csproj file itself, and specify the same path in the outputs array, rather than referencing a parameter.

Some of the reasoning behind that is here: https://www.nx-dotnet.com/docs/core/guides/incremental-builds#optimizing-cache-hits

Essentially, when you provide `--output` as an option to `dotnet build`, the resulting output is not able to be found by consumer builds when running with `--no-dependencies`. We recommend using `--no-dependencies` to allow Nx to orchestrate the builds, and as such no longer recommend using the `--output` property on the executor.

It is true that the path should probably be relative to workspace root though, so I'd be open to a PR that normalizes the path (even if its not something I'd recommend using)

**Comment by EelcoLos** [comment]
don't think this is happening any more
