### ISSUE TITLE
`yarn publish-local` broken.  e2e-registry went missing from package.json

### ISSUE THREAD

**Issue by Tungsten78** [nx-dotnet/nx-dotnet#610]
Haven't narrowed to a specific commit.

**Comment by Tungsten78** [comment]
https://github.com/nx-dotnet/nx-dotnet/commit/ec342ae2699b7ca5fad0aee717d67ded3c0a9524#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by Tungsten78** [comment]
@AgentEnder - would you mind documenting your current workflow?  maybe in #89?

**Comment by Tungsten78** [comment]
I took a look `sandbox` will work good for local testing
* I'm think it makes `publish-local` redundant.

If you agree I can rip it out and try to document it somewhere (please suggest a good spot).

**Comment by AgentEnder** [comment]
Yeah, feel free to open a pr ripping it out and documenting yarn sandbox. Somewhere in CONTRIBUTING.md would be good...

That said, I'm not sure we have a contributing.md.

Since you've recently onboarded as a contributor, it may be good if you want to list a few tips in that file even if it means creating it.

**Comment by AgentEnder** [comment]
Yeah, feel free to open a pr ripping it out and documenting yarn sandbox. Somewhere in CONTRIBUTING.md would be good...

That said, I'm not sure we have a contributing.md.

Since you've recently onboarded as a contributor, it may be good if you want to list a few tips in that file even if it means creating it.
