### ISSUE TITLE
[Feature] Add option for standalone projects

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#70]
**Is your feature request related to a problem? Please describe.**
I recently migrated my workspace to Nx 12.5 and switched to standalone project configurations. When I added a new .NET project to my workspace, the new project used the old `nx.json` and `workspace.json` configuration.

**Describe the solution you'd like**
I would like a new option added to the app and lib generators that generates the project configuration in standalone format.

**Describe alternatives you've considered**
Alternatively, I could write my own wrapper generator/script that moves the project configuration after it has been written, or I use the Nx-official generator to migrate the newly created project into the new format.

**Additional context**
Generating project configuration in the new standalone format is a one-parameter change to `addProjectConfiguration`. The app and lib generators just need a new parameter which will be passed through to `addProjectConfiguration`.

**Comment by AgentEnder** [comment]
Hehe, funny enough I was the one who implemented this feature in Nx (and thus updated the nrwl generators with the option). Adding support for this is pretty simple. Heres what needs to be done:

1. Update schema.json files to add the option
2. Add it to typings
3. Pass value as 3rd parameter to addProjectConfiguration

Notably adding this 3rd parameter may be a breaking change since it did not exist prior to nx 12.5, so the minimum supported nx version may need to be bumped to nx 12.5. I'll have to check this against earlier versions before bumping it. We should also migrate this repo to 12.5 and convert to `project.json` files in the meantime.

I am open to PR's for any of this :smile:
