### ISSUE TITLE
[Feature] dotnet libraries not cache invalidated when package.json updates

### ISSUE THREAD

**Issue by EelcoLos** [nx-dotnet/nx-dotnet#759]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when `package.json` updates and the cache invalidates on the `dotnet` libraries.

**Describe the solution you'd like**
Something along the line of using nx' 16.5 `input: [{externaldependencies: nx-dotnet}]` to not have the libraries trigger update only when `@nx-dotnet/core` updates

**Describe alternatives you've considered**
Other than adding the `dotnet` libraries to `.nxignore` or removing the package entirely, not really. It's a nuisance, not breaking.

**Comment by AgentEnder** [comment]
Setting externalDependencies for them is the correct thing here, just remember that inputs arrays are not merged so you'll need to include your other namedInputs.

There are several caveats to how this would be done so I don't think its something that we will generate for folks, rather its something that will need to be done on a repo-by-repo basis since peoples inputs + outputs tend to be set up slightly differently and we would want to avoid false cache hits.

It seems like you know how to fix this for your repo, so I'm going to go ahead and close this out. Feel free to let me know if any more help is needed.

**Comment by EelcoLos** [comment]
I tried fixing it myself, though this didn't seem to work. Maybe my premise is wrong or my setup is wrong:

My premise with this case:
1. Have `"inputs": [{ "externalDependencies": ["@nx-dotnet/core"] }]` on every task with a `dotnet` project
1. update `package.json` with dependencies not being `@nx-dotnet/core`. 
1. Run `npx nx run-many -t build lint test`. The `dotnet` libraries should returned to be cached and not being built, linted or tested

When i tried this this morning with these targets:
```json
"targets": {
		"build": {
			"executor": "@nx-dotnet/core:build",
			"inputs": [{ "externalDependencies": ["@nx-dotnet/core"] }],
			"outputs": ["{workspaceRoot}/dist/libs/shared/startup"],
			"options": {
				"configuration": "Debug"
			},
			"configurations": {
				"production": {
					"configuration": "Release"
				}
			}
		},
		"lint": {
			"executor": "@nx-dotnet/core:format",
			"inputs": [{ "externalDependencies": ["@nx-dotnet/core"] }]
		},
		"lint-fix": {
			"executor": "@nx-dotnet/core:format",
			"inputs": [{ "externalDependencies": ["@nx-dotnet/core"] }],
			"options": {
				"fix": true
			}
		}
	},
```
Do I _need_ the `namedInputs` or is this a viable setup. If so, why is the `package.json` update still triggering these tasks to be run out of cache hit?
