### ISSUE TITLE
[Feature] Integrate with .NET 8.0 MSBuild Project Cache Plugin

### ISSUE THREAD

**Issue by Cjewett** [nx-dotnet/nx-dotnet#793]
**Is your feature request related to a problem? Please describe.**
We evaluated using nx-dotnet in the past and were not huge fans of having to introduce Node.js dependencies into a C# repository. It's a departure from what developers are expecting and adds an extra layer of complexity that we weren't excited about as a team. In addition to that we felt that the tooling wasn't accurate enough in certain scenarios such as altering Directory.Packages.props, Directory.Build.props, runsettings, etc. Due to this we've been investigating other options. 

**Describe the solution you'd like**
With .NET 8.0 and an updated MSBuild they are releasing new functionality that allows you to create Plugins that integrate with MSBuild. These Plugins can be used for distributed build cache scenarios and is one of the main examples in their documentation. 

https://github.com/dotnet/msbuild/pull/9329
https://github.com/dfederm/msbuild/blob/project-cache-docs/documentation/specs/project-cache.md 

Our hope is that we shouldn't need to inherit any Node.js dependencies to integrate with nx-cloud's caching functionality. It may possible to reduce the C# ecosystems effort to integrate with nx-cloud to:
1. Update Directory.Build.props with nxCloudAccessToken and nxCloudUrl.
2. Add nx-msbuild-plugin to the whole repository via [Global References](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#global-package-references), or add it to individual C# projects. The inclusion of the plugin will be all you need to integrate with nx-cloud. 

The nx cli functionality isn't valuable to us, so that is another reason we don't care to inherit all of the Node.js dependencies. 

**Describe alternatives you've considered**
Obviously the solution we'd like is a departure from how this works today and many may find the nx cli functionality for the C# ecosystem valuable. Regardless of what happens we think it would be valuable for some MSBuild plugin to be created because it would provide more accurate cache results and evolve with the MSBuild ecosystem. Even if that plugin is used as a bridge between nx-dotnet and MSBuild rather than a direct integration with nx-cloud's API. 

**Additional context**
I had asked in the nx slack about hitting the nx-cloud API directly with custom tooling and it seemed like a situation where the nx organization did not expect custom tools to use it. As a result we've been hesitant to attempt a proof of concept of what I've described above. I wanted to use this discussion to try and facilitate some of the question I had there as well. If the team doesn't find this request valuable is the nx team open to a community contribution that integrates MSBuild directly with nx-cloud's API? What about private tooling that does so?

**Comment by AgentEnder** [comment]
Hey @Cjewett, thanks for the issue + associated discussion. I don't think this is a route I'd want to take the plugin. While it could be cool, it would integrate a lot of additional risk in terms of long term maintenance and make compatibility a lot more fragile.

The nx-cloud API's are currently quite stable, but they are not guaranteed to stay stable for any given major version of Nx or similar, as we have ways of updating the cloud task runner to handle API changes. Doing this would tightly couple us to the cloud API, and make things a bit more shaky in that respect.

Additionally, Nx Cloud is more than just caching and to truly take advantage of it and DTE, you can't have msbuild be the main orchestrator for your tasks. This is why we recommend turning on `--noDependencies` for builds. By letting Nx itself be the main tasks orchestrator in the repo, and only building single units with msbuild at any given time, Nx's caching can happen when it needs to, and Nx Cloud can distribute your tasks easily across multiple machines.

In order to integrate that into msbuild, we'd essentially have to rewrite the a large part of DTE and the cloud tasks runners, and it wouldn't be feasible in the long run. Aside from this feasibility, I don't have the expertise nor the free time to develop said expertise in msbuild plugin development, and wouldn't be an effective maintainer for that use case.

While the primary use case of nx-dotnet is mixed-language repos, where its already normal to have node_modules and such, you can use Nx + nx-dotnet w/o node_modules. This does still rely on node and such in the background, but its a lot more hidden away. Here's some reference material if you are curious about it:
- https://github.com/AgentEnder/encapsulated-dotnet-repo/
- https://nx.dev/recipes/installation/install-non-javascript

I'm going to close this out because its not something that **_this_** plugin should do. It would be interesting to see another plugin take a stab at it, but even then I think you'd be missing out on DTE and thus some of the other exciting stuff coming down the nx-cloud pipeline. Feel free to respond on here and we can discuss a bit further if you are having any other issues or have other questions and ideas.

**Comment by Cjewett** [comment]
@AgentEnder Totally understand where you're coming from. We'll be playing around with the new functionality over the next few weeks or month(s) since Holidays are coming around. One of the pieces we want to investigate is if we think an integration with the nx-cloud API makes sense, so I'll update this thread as needed.
