### ISSUE TITLE
[BUG] `"noDependencies": false` option has no effect

### ISSUE THREAD

**Issue by Den-dp** [nx-dotnet/nx-dotnet#812]
### Current Behavior

`"noDependencies": false` option has no effect since dotnet cli expects `--no-dependencies` to be a boolean parameter

F.e.:
```json
{
  "$schema": "../node_modules/nx/schemas/project-schema.json",
  "name": "foo-lib",
  "projectType": "library",
  "targets": {
    "build": {
      "options": {
        "noDependencies": false
      }
    }
  }
}
```
results in
```sh
> nx run foo-lib:build

Executing Command: dotnet "--version"
7.0.311
Executing Command: dotnet "build" "C:\source\foo-lib\foo-lib.csproj" "--no-dependencies" "false" "--verbosity" "minimal"
```
so here we still have enabled --no-dependencies despite the passing "false"

### Expected Behavior

`--no-dependencies` parameter must be removed from dotnet cli commands when noDependencies: false is configured

### Steps to Reproduce

1. project.json
```json
{
  "$schema": "../node_modules/nx/schemas/project-schema.json",
  "name": "foo-lib",
  "projectType": "library",
  "targets": {
    "build": {
      "options": {
        "configuration": "Debug",
        "noDependencies": false
      }
    }
  }
}
```
2. nx run foo-lib:build
3. look at executing dotnet command

### Nx Report

```shell
Node   : 18.17.1
   OS     : win32-x64
   npm    : 9.9.2

   nx (global)        : 17.1.3
   nx                 : 17.1.3
   @nx/js             : 17.1.3
   @nx/linter         : 17.1.3
   @nx/eslint         : 17.1.3
   @nx/workspace      : 17.1.3
   @nx/devkit         : 17.1.3
   @nx/eslint-plugin  : 17.1.3
   @nx/playwright     : 17.1.3
   @nrwl/tao          : 17.1.3
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core : 2.1.2
```

### nx.json

```json
{
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ]
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore",
        "{workspaceRoot}/eslint.config.js"
      ]
    }
  },
  "affected": {
    "defaultBase": "master"
  },
  "plugins": [
    {
      "plugin": "@nx-dotnet/core",
      "options": {
        "nugetPackages": {}
      }
    }
  ]
}
```

### Additional Information

I'm aware of https://www.nx-dotnet.com/docs/core/guides/incremental-builds reasoning, but unfortunately, we had to use `"noDependencies": false`.

**Comment by EchelonFour** [comment]
I am getting a similar bug with running tests. Even with default options it will run the command:
`dotnet "test" "Test.csproj" "--blame" "false" "--blame-crash" "false" "--blame-crash-collect-always" "false" "--blame-hang" "false"`
and the test tool gets confused by all the falses.
The bug [comes from here](https://github.com/nx-dotnet/nx-dotnet/blob/b673b2f3906b31ede0b207c1ec426cc45a4886f5/packages/utils/src/lib/utility-functions/parameters.ts#L32-L37). When the option is false, rather than not pass the option to the cli, it will pass the word `"false"`. It appears to be a deliberate change for the format options, but it has clearly had some unintended side effects.
